# Generated by Django 5.2.7 on 2026-09-06 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('company', 'Bedrijf'), ('person', 'Particulier')], default='company', max_length=12)),
                ('legal_name', models.CharField(max_length=200, verbose_name='naam')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='handelsnaam')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('kvk_number', models.CharField(blank=True, max_length=20, verbose_name='KvK-nummer')),
                ('vat_id', models.CharField(blank=True, max_length=32, verbose_name='btw-identificatienummer')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='straat en huisnummer')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='postcode')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='plaats')),
                ('billing_address', models.CharField(blank=True, max_length=200, verbose_name='afwijkend factuuradres')),
                ('billing_postal_code', models.CharField(blank=True, max_length=12, verbose_name='factuurpostcode')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='factuurplaats')),
                ('payment_term_days', models.PositiveSmallIntegerField(default=14, verbose_name='betalingstermijn')),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('active', 'Actief'), ('inactive', 'Inactief'), ('archived', 'Gearchiveerd')], db_index=True, default='active', max_length=12)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, verbose_name='interne notities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to='core.membership')),
            ],
            options={
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='voornaam')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='achternaam')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='functie')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_primary', models.BooleanField(default=False, verbose_name='primair contact')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.organization')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.customer')),
            ],
            options={
                'ordering': ['-is_primary', 'first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('note', 'Notitie'), ('system', 'Systeem'), ('email', 'E-mail'), ('call', 'Telefoongesprek')], default='note', max_length=15)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_activities', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'status'], name='core_custom_organiz_ceed7e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'legal_name'], name='core_custom_organiz_699ced_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('kvk_number', ''), _negated=True), fields=('organization', 'kvk_number'), name='unique_org_kvk'),
        ),
    ]
