# Generated by Django 5.2.7 on 2026-09-06 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_quote_quoteline_documentsequence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('invoice', 'Factuur'), ('credit', 'Creditfactuur')], default='invoice', max_length=10)),
                ('number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Concept'), ('submitted', 'Ter goedkeuring'), ('approved', 'Goedgekeurd'), ('rejected', 'Afgewezen'), ('queued', 'Klaar voor verzending'), ('sent', 'Verzonden'), ('partial', 'Deels betaald'), ('paid', 'Betaald'), ('overdue', 'Vervallen'), ('credited', 'Gecrediteerd')], db_index=True, default='draft', max_length=20)),
                ('title', models.CharField(default='Factuur', max_length=200)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50)),
                ('rejection_reason', models.TextField(blank=True)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('customer_address_snapshot', models.CharField(blank=True, max_length=300)),
                ('customer_vat_snapshot', models.CharField(blank=True, max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.organization')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_invoices', to='core.invoice')),
                ('source_quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='core.quote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit', models.CharField(default='stuk', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='core.organization')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=20)),
                ('document_id', models.UUIDField()),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('queued', 'In wachtrij'), ('sent', 'Verzonden'), ('failed', 'Mislukt')], default='queued', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='core.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='core_emaild_organiz_e81cdc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='unique_org_invoice_number'),
        ),
    ]
