# Generated by Django 5.2.7 on 2026-09-06 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoice_invoiceline_payment_emaildelivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#239F7F', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_types', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reminder_minutes', models.PositiveIntegerField(default=30)),
                ('recurrence', models.CharField(choices=[('none', 'Niet herhalen'), ('daily', 'Dagelijks'), ('weekly', 'Wekelijks'), ('monthly', 'Maandelijks')], default='none', max_length=10)),
                ('recurrence_until', models.DateField(blank=True, null=True)),
                ('series_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.organization')),
                ('participants', models.ManyToManyField(related_name='appointments', to='core.membership')),
                ('appointment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.appointmenttype')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.AddConstraint(
            model_name='appointmenttype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_org_appointment_type'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['organization', 'start', 'end'], name='core_appoin_organiz_913e0e_idx'),
        ),
    ]
