# Generated by Django 5.2.7 on 2026-09-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_board_boardcolumn_task_taskattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profiles/avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('system', 'Systeeminstelling'), ('light', 'Light mode'), ('dark', 'Dark mode')], default='system', max_length=10),
        ),
    ]
