# Generated by Django 5.2.7 on 2026-09-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_invoice_archived_at_invoice_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_email_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
