# Generated by Django 5.2.17 on 2026-09-06 19:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_product_minimum_stock_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.models.workorder_photo_path),
        ),
    ]
