from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
urlpatterns=[
    path('health/',views.health,name='health'),
    path('login/',views.SecureLoginView.as_view(),name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('wachtwoord/',auth_views.PasswordChangeView.as_view(template_name='core/password_change.html',success_url='/instellingen/'),name='password_change'),
    path('instellingen/',views.profile_settings,name='profile_settings'),path('profiel/<int:user_id>/avatar/',views.profile_avatar,name='profile_avatar'),
    path('beheer/e-mail/',views.email_settings,name='email_settings'),path('beheer/e-mail/test/',views.email_settings_test,name='email_settings_test'),
    path('',views.dashboard,name='dashboard'),
    path('klanten/',views.customer_list,name='customer_list'),path('klanten/nieuw/',views.customer_create,name='customer_create'),
    path('klanten/importeren/',views.customer_import,name='customer_import'),path('klanten/exporteren/',views.customer_export,name='customer_export'),
    path('klanten/<uuid:customer_id>/',views.customer_detail,name='customer_detail'),path('klanten/<uuid:customer_id>/bewerken/',views.customer_edit,name='customer_edit'),
    path('klanten/<uuid:customer_id>/archiveren/',views.customer_archive,name='customer_archive'),path('klanten/<uuid:customer_id>/activiteit/',views.customer_note,name='customer_note'),
    path('klanten/<uuid:customer_id>/contacten/nieuw/',views.contact_add,name='contact_add'),path('klanten/<uuid:customer_id>/contacten/<uuid:contact_id>/',views.contact_edit,name='contact_edit'),
    path('klanten/<uuid:customer_id>/contacten/<uuid:contact_id>/archiveren/',views.contact_archive,name='contact_archive'),
    path('producten/',views.product_list,name='product_list'),path('producten/nieuw/',views.product_form,name='product_create'),path('producten/<uuid:product_id>/',views.product_form,name='product_edit'),path('producten/<uuid:product_id>/verwijderen/',views.product_delete,name='product_delete'),
    path('offertes/',views.quote_list,name='quote_list'),path('offertes/nieuw/',views.quote_create,name='quote_create'),
    path('offertes/<uuid:quote_id>/',views.quote_detail,name='quote_detail'),path('offertes/<uuid:quote_id>/bewerken/',views.quote_edit,name='quote_edit'),path('offertes/<uuid:quote_id>/verwijderen/',views.quote_delete,name='quote_delete'),path('offertes/<uuid:quote_id>/pdf/',views.quote_pdf,name='quote_pdf'),
    path('offertes/<uuid:quote_id>/regels/',views.quote_line_add,name='quote_line_add'),path('offertes/<uuid:quote_id>/regels/<uuid:line_id>/verwijderen/',views.quote_line_delete,name='quote_line_delete'),
    path('offertes/<uuid:quote_id>/indienen/',views.quote_submit,name='quote_submit'),path('offertes/<uuid:quote_id>/goedkeuren/',views.quote_approve,name='quote_approve'),path('offertes/<uuid:quote_id>/afwijzen/',views.quote_reject,name='quote_reject'),
    path('facturen/',views.invoice_list,name='invoice_list'),path('facturen/nieuw/',views.invoice_create,name='invoice_create'),path('facturen/van-offerte/<uuid:quote_id>/',views.invoice_from_quote,name='invoice_from_quote'),
    path('facturen/<uuid:invoice_id>/',views.invoice_detail,name='invoice_detail'),path('facturen/<uuid:invoice_id>/bewerken/',views.invoice_edit,name='invoice_edit'),path('facturen/<uuid:invoice_id>/verwijderen/',views.invoice_delete,name='invoice_delete'),path('facturen/<uuid:invoice_id>/pdf/',views.invoice_pdf,name='invoice_pdf'),
    path('facturen/<uuid:invoice_id>/regels/',views.invoice_line_add,name='invoice_line_add'),path('facturen/<uuid:invoice_id>/regels/<uuid:line_id>/verwijderen/',views.invoice_line_delete,name='invoice_line_delete'),
    path('facturen/<uuid:invoice_id>/indienen/',views.invoice_submit,name='invoice_submit'),path('facturen/<uuid:invoice_id>/goedkeuren/',views.invoice_approve,name='invoice_approve'),path('facturen/<uuid:invoice_id>/afwijzen/',views.invoice_reject,name='invoice_reject'),
    path('facturen/<uuid:invoice_id>/betaling/',views.payment_add,name='payment_add'),path('facturen/<uuid:invoice_id>/credit/',views.credit_create,name='credit_create'),
    path('verzending/',views.outbox,name='outbox'),path('verzending/verstuur-goedgekeurd/',views.dispatch_approved,name='dispatch_approved'),path('verzending/<uuid:delivery_id>/verwijderen/',views.delivery_delete,name='delivery_delete'),
    path('agenda/',views.calendar_view,name='calendar'),path('agenda/nieuw/',views.appointment_create,name='appointment_create'),path('agenda/<uuid:appointment_id>/',views.appointment_detail,name='appointment_detail'),path('agenda/<uuid:appointment_id>/bewerken/',views.appointment_edit,name='appointment_edit'),path('agenda/<uuid:appointment_id>/annuleren/',views.appointment_cancel,name='appointment_cancel'),
    path('taken/',views.board_list,name='board_list'),path('taken/borden/nieuw/',views.board_create,name='board_create'),path('taken/borden/<uuid:board_id>/',views.board_detail,name='board_detail'),
    path('taken/borden/<uuid:board_id>/kolommen/nieuw/',views.column_add,name='column_add'),path('taken/borden/<uuid:board_id>/kolommen/<uuid:column_id>/',views.column_edit,name='column_edit'),
    path('taken/borden/<uuid:board_id>/nieuw/',views.task_create,name='task_create'),path('taken/borden/<uuid:board_id>/<uuid:task_id>/',views.task_detail,name='task_detail'),path('taken/borden/<uuid:board_id>/<uuid:task_id>/bewerken/',views.task_edit,name='task_edit'),path('taken/borden/<uuid:board_id>/<uuid:task_id>/verplaatsen/',views.task_move,name='task_move'),path('taken/borden/<uuid:board_id>/<uuid:task_id>/archiveren/',views.task_archive,name='task_archive'),
    path('taken/borden/<uuid:board_id>/<uuid:task_id>/checklist/',views.checklist_add,name='checklist_add'),path('taken/borden/<uuid:board_id>/<uuid:task_id>/checklist/<uuid:item_id>/',views.checklist_toggle,name='checklist_toggle'),path('taken/borden/<uuid:board_id>/<uuid:task_id>/opmerking/',views.task_comment,name='task_comment'),path('taken/borden/<uuid:board_id>/<uuid:task_id>/bijlage/',views.task_attachment,name='task_attachment'),path('taken/borden/<uuid:board_id>/<uuid:task_id>/bijlage/<uuid:attachment_id>/',views.attachment_download,name='attachment_download'),
    path('team/',views.team,name='team'),path('team/nieuw/',views.team_add,name='team_add'),
    path('team/<uuid:membership_id>/bewerken/',views.team_edit,name='team_edit'),
    path('team/<uuid:membership_id>/verwijderen/',views.team_remove,name='team_remove'),
    path('team/<uuid:membership_id>/status/',views.team_toggle,name='team_toggle'),
]
